// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_metrics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listDays = `-- name: ListDays :many
SELECT day_key, steps, pai_score,
       COALESCE(readiness, computed_readiness) AS readiness, spo2_avg, hrv_rmssd,
       resting_hr, resp_rate_avg, stress_avg, sleep_score, sleep_mins,
       sleep_deep_mins, sleep_rem_mins, sleep_light_mins, temp_avg_c,
       nap_count, workout_count, activity_session_count, source_session_id, updated_at
FROM daily_metrics
WHERE day_key >= $1 AND day_key <= $2
ORDER BY day_key DESC
`

type ListDaysParams struct {
	DayKey   pgtype.Date `json:"day_key"`
	DayKey_2 pgtype.Date `json:"day_key_2"`
}

type ListDaysRow struct {
	DayKey               pgtype.Date        `json:"day_key"`
	Steps                int32              `json:"steps"`
	PaiScore             pgtype.Int4        `json:"pai_score"`
	Readiness            pgtype.Int4        `json:"readiness"`
	Spo2Avg              pgtype.Int4        `json:"spo2_avg"`
	HrvRmssd             pgtype.Int4        `json:"hrv_rmssd"`
	RestingHr            pgtype.Int4        `json:"resting_hr"`
	RespRateAvg          pgtype.Int4        `json:"resp_rate_avg"`
	StressAvg            pgtype.Int4        `json:"stress_avg"`
	SleepScore           pgtype.Int4        `json:"sleep_score"`
	SleepMins            pgtype.Int4        `json:"sleep_mins"`
	SleepDeepMins        pgtype.Int4        `json:"sleep_deep_mins"`
	SleepRemMins         pgtype.Int4        `json:"sleep_rem_mins"`
	SleepLightMins       pgtype.Int4        `json:"sleep_light_mins"`
	TempAvgC             pgtype.Numeric     `json:"temp_avg_c"`
	NapCount             int32              `json:"nap_count"`
	WorkoutCount         int32              `json:"workout_count"`
	ActivitySessionCount int32              `json:"activity_session_count"`
	SourceSessionID      pgtype.Text        `json:"source_session_id"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

// readiness prefers the device's 0x39 score, falling back to our computed one.
func (q *Queries) ListDays(ctx context.Context, arg ListDaysParams) ([]ListDaysRow, error) {
	rows, err := q.db.Query(ctx, listDays, arg.DayKey, arg.DayKey_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDaysRow{}
	for rows.Next() {
		var i ListDaysRow
		if err := rows.Scan(
			&i.DayKey,
			&i.Steps,
			&i.PaiScore,
			&i.Readiness,
			&i.Spo2Avg,
			&i.HrvRmssd,
			&i.RestingHr,
			&i.RespRateAvg,
			&i.StressAvg,
			&i.SleepScore,
			&i.SleepMins,
			&i.SleepDeepMins,
			&i.SleepRemMins,
			&i.SleepLightMins,
			&i.TempAvgC,
			&i.NapCount,
			&i.WorkoutCount,
			&i.ActivitySessionCount,
			&i.SourceSessionID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDayMetric = `-- name: UpsertDayMetric :exec
INSERT INTO daily_metrics (
  day_key, steps, pai_score, readiness, spo2_avg, hrv_rmssd,
  resting_hr, resp_rate_avg, stress_avg, sleep_score, sleep_mins,
  sleep_deep_mins, sleep_rem_mins, sleep_light_mins, temp_avg_c,
  nap_count, workout_count, activity_session_count, source_session_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
)
ON CONFLICT (day_key) DO UPDATE SET
  -- Steps arrive as incremental deltas (minutes since last sync), not the
  -- full-day cumulative total, so we ADD rather than replace.
  steps = daily_metrics.steps + GREATEST(EXCLUDED.steps, 0),
  pai_score = COALESCE(EXCLUDED.pai_score, daily_metrics.pai_score),
  readiness = COALESCE(EXCLUDED.readiness, daily_metrics.readiness),
  spo2_avg = COALESCE(EXCLUDED.spo2_avg, daily_metrics.spo2_avg),
  hrv_rmssd = COALESCE(EXCLUDED.hrv_rmssd, daily_metrics.hrv_rmssd),
  resting_hr = COALESCE(EXCLUDED.resting_hr, daily_metrics.resting_hr),
  resp_rate_avg = COALESCE(EXCLUDED.resp_rate_avg, daily_metrics.resp_rate_avg),
  stress_avg = COALESCE(EXCLUDED.stress_avg, daily_metrics.stress_avg),
  sleep_score = COALESCE(EXCLUDED.sleep_score, daily_metrics.sleep_score),
  sleep_mins = COALESCE(EXCLUDED.sleep_mins, daily_metrics.sleep_mins),
  sleep_deep_mins = COALESCE(EXCLUDED.sleep_deep_mins, daily_metrics.sleep_deep_mins),
  sleep_rem_mins = COALESCE(EXCLUDED.sleep_rem_mins, daily_metrics.sleep_rem_mins),
  sleep_light_mins = COALESCE(EXCLUDED.sleep_light_mins, daily_metrics.sleep_light_mins),
  temp_avg_c = COALESCE(EXCLUDED.temp_avg_c, daily_metrics.temp_avg_c),
  nap_count = GREATEST(daily_metrics.nap_count, EXCLUDED.nap_count),
  workout_count = GREATEST(daily_metrics.workout_count, EXCLUDED.workout_count),
  activity_session_count = GREATEST(daily_metrics.activity_session_count, EXCLUDED.activity_session_count),
  source_session_id = EXCLUDED.source_session_id,
  updated_at = NOW()
`

type UpsertDayMetricParams struct {
	DayKey               pgtype.Date    `json:"day_key"`
	Steps                int32          `json:"steps"`
	PaiScore             pgtype.Int4    `json:"pai_score"`
	Readiness            pgtype.Int4    `json:"readiness"`
	Spo2Avg              pgtype.Int4    `json:"spo2_avg"`
	HrvRmssd             pgtype.Int4    `json:"hrv_rmssd"`
	RestingHr            pgtype.Int4    `json:"resting_hr"`
	RespRateAvg          pgtype.Int4    `json:"resp_rate_avg"`
	StressAvg            pgtype.Int4    `json:"stress_avg"`
	SleepScore           pgtype.Int4    `json:"sleep_score"`
	SleepMins            pgtype.Int4    `json:"sleep_mins"`
	SleepDeepMins        pgtype.Int4    `json:"sleep_deep_mins"`
	SleepRemMins         pgtype.Int4    `json:"sleep_rem_mins"`
	SleepLightMins       pgtype.Int4    `json:"sleep_light_mins"`
	TempAvgC             pgtype.Numeric `json:"temp_avg_c"`
	NapCount             int32          `json:"nap_count"`
	WorkoutCount         int32          `json:"workout_count"`
	ActivitySessionCount int32          `json:"activity_session_count"`
	SourceSessionID      pgtype.Text    `json:"source_session_id"`
}

func (q *Queries) UpsertDayMetric(ctx context.Context, arg UpsertDayMetricParams) error {
	_, err := q.db.Exec(ctx, upsertDayMetric,
		arg.DayKey,
		arg.Steps,
		arg.PaiScore,
		arg.Readiness,
		arg.Spo2Avg,
		arg.HrvRmssd,
		arg.RestingHr,
		arg.RespRateAvg,
		arg.StressAvg,
		arg.SleepScore,
		arg.SleepMins,
		arg.SleepDeepMins,
		arg.SleepRemMins,
		arg.SleepLightMins,
		arg.TempAvgC,
		arg.NapCount,
		arg.WorkoutCount,
		arg.ActivitySessionCount,
		arg.SourceSessionID,
	)
	return err
}
