// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health_samples.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteHealthSamplesBySession = `-- name: DeleteHealthSamplesBySession :exec
DELETE FROM health_samples WHERE sync_session_id = $1
`

func (q *Queries) DeleteHealthSamplesBySession(ctx context.Context, syncSessionID string) error {
	_, err := q.db.Exec(ctx, deleteHealthSamplesBySession, syncSessionID)
	return err
}

const insertHealthSample = `-- name: InsertHealthSample :exec
INSERT INTO health_samples (sync_session_id, metric, day_key, sampled_at, value)
VALUES ($1, $2, $3, $4, $5)
`

type InsertHealthSampleParams struct {
	SyncSessionID string             `json:"sync_session_id"`
	Metric        string             `json:"metric"`
	DayKey        string             `json:"day_key"`
	SampledAt     pgtype.Timestamptz `json:"sampled_at"`
	Value         pgtype.Numeric     `json:"value"`
}

func (q *Queries) InsertHealthSample(ctx context.Context, arg InsertHealthSampleParams) error {
	_, err := q.db.Exec(ctx, insertHealthSample,
		arg.SyncSessionID,
		arg.Metric,
		arg.DayKey,
		arg.SampledAt,
		arg.Value,
	)
	return err
}

const listHealthSamples = `-- name: ListHealthSamples :many
SELECT metric, day_key, sampled_at, value
FROM health_samples
WHERE day_key >= $1 AND day_key <= $2
ORDER BY sampled_at ASC
`

type ListHealthSamplesParams struct {
	DayKey   string `json:"day_key"`
	DayKey_2 string `json:"day_key_2"`
}

type ListHealthSamplesRow struct {
	Metric    string             `json:"metric"`
	DayKey    string             `json:"day_key"`
	SampledAt pgtype.Timestamptz `json:"sampled_at"`
	Value     pgtype.Numeric     `json:"value"`
}

func (q *Queries) ListHealthSamples(ctx context.Context, arg ListHealthSamplesParams) ([]ListHealthSamplesRow, error) {
	rows, err := q.db.Query(ctx, listHealthSamples, arg.DayKey, arg.DayKey_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHealthSamplesRow{}
	for rows.Next() {
		var i ListHealthSamplesRow
		if err := rows.Scan(
			&i.Metric,
			&i.DayKey,
			&i.SampledAt,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
