// Code generated by sqlc. DO NOT EDIT.
// source: health_samples.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listHealthSamples = `-- name: ListHealthSamples :many
SELECT metric, day_key, sampled_at, value
FROM health_samples
WHERE day_key >= $1 AND day_key <= $2
ORDER BY sampled_at ASC
`

type ListHealthSamplesParams struct {
	DayKey   pgtype.Date `json:"day_key"`
	DayKey_2 pgtype.Date `json:"day_key_2"`
}

type ListHealthSamplesRow struct {
	Metric    string             `json:"metric"`
	DayKey    pgtype.Date        `json:"day_key"`
	SampledAt pgtype.Timestamptz `json:"sampled_at"`
	Value     pgtype.Numeric     `json:"value"`
}

func (q *Queries) ListHealthSamples(ctx context.Context, arg ListHealthSamplesParams) ([]ListHealthSamplesRow, error) {
	rows, err := q.db.Query(ctx, listHealthSamples, arg.DayKey, arg.DayKey_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHealthSamplesRow{}
	for rows.Next() {
		var i ListHealthSamplesRow
		if err := rows.Scan(&i.Metric, &i.DayKey, &i.SampledAt, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const upsertHealthSample = `-- name: UpsertHealthSample :exec
INSERT INTO health_samples (metric, day_key, sampled_at, value, source_session_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (metric, sampled_at) DO UPDATE SET
  value = EXCLUDED.value,
  day_key = EXCLUDED.day_key,
  source_session_id = EXCLUDED.source_session_id
`

type UpsertHealthSampleParams struct {
	Metric          string             `json:"metric"`
	DayKey          pgtype.Date        `json:"day_key"`
	SampledAt       pgtype.Timestamptz `json:"sampled_at"`
	Value           pgtype.Numeric     `json:"value"`
	SourceSessionID string             `json:"source_session_id"`
}

func (q *Queries) UpsertHealthSample(ctx context.Context, arg UpsertHealthSampleParams) error {
	_, err := q.db.Exec(ctx, upsertHealthSample,
		arg.Metric, arg.DayKey, arg.SampledAt, arg.Value, arg.SourceSessionID,
	)
	return err
}
