// Code generated by sqlc. DO NOT EDIT.
// source: heart_rate_samples.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listHeartRateSamples = `-- name: ListHeartRateSamples :many
SELECT day_key, sampled_at, bpm
FROM heart_rate_samples
WHERE day_key >= $1 AND day_key <= $2
ORDER BY sampled_at ASC
`

type ListHeartRateSamplesParams struct {
	DayKey   pgtype.Date `json:"day_key"`
	DayKey_2 pgtype.Date `json:"day_key_2"`
}

type ListHeartRateSamplesRow struct {
	DayKey    pgtype.Date        `json:"day_key"`
	SampledAt pgtype.Timestamptz `json:"sampled_at"`
	Bpm       int16              `json:"bpm"`
}

func (q *Queries) ListHeartRateSamples(ctx context.Context, arg ListHeartRateSamplesParams) ([]ListHeartRateSamplesRow, error) {
	rows, err := q.db.Query(ctx, listHeartRateSamples, arg.DayKey, arg.DayKey_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHeartRateSamplesRow{}
	for rows.Next() {
		var i ListHeartRateSamplesRow
		if err := rows.Scan(&i.DayKey, &i.SampledAt, &i.Bpm); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const upsertHeartRateSample = `-- name: UpsertHeartRateSample :exec
INSERT INTO heart_rate_samples (sampled_at, day_key, bpm, source_session_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (sampled_at) DO UPDATE SET
  bpm = EXCLUDED.bpm,
  day_key = EXCLUDED.day_key,
  source_session_id = EXCLUDED.source_session_id
`

type UpsertHeartRateSampleParams struct {
	SampledAt       pgtype.Timestamptz `json:"sampled_at"`
	DayKey          pgtype.Date        `json:"day_key"`
	Bpm             int16              `json:"bpm"`
	SourceSessionID string             `json:"source_session_id"`
}

func (q *Queries) UpsertHeartRateSample(ctx context.Context, arg UpsertHeartRateSampleParams) error {
	_, err := q.db.Exec(ctx, upsertHeartRateSample,
		arg.SampledAt, arg.DayKey, arg.Bpm, arg.SourceSessionID,
	)
	return err
}
