// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: heart_rate_samples.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listHeartRateSamples = `-- name: ListHeartRateSamples :many
SELECT day_key, sampled_at, bpm
FROM heart_rate_samples
WHERE day_key >= $1 AND day_key <= $2
ORDER BY sampled_at ASC
`

type ListHeartRateSamplesParams struct {
	DayKey   pgtype.Date `json:"day_key"`
	DayKey_2 pgtype.Date `json:"day_key_2"`
}

type ListHeartRateSamplesRow struct {
	DayKey    pgtype.Date        `json:"day_key"`
	SampledAt pgtype.Timestamptz `json:"sampled_at"`
	Bpm       int16              `json:"bpm"`
}

func (q *Queries) ListHeartRateSamples(ctx context.Context, arg ListHeartRateSamplesParams) ([]ListHeartRateSamplesRow, error) {
	rows, err := q.db.Query(ctx, listHeartRateSamples, arg.DayKey, arg.DayKey_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHeartRateSamplesRow{}
	for rows.Next() {
		var i ListHeartRateSamplesRow
		if err := rows.Scan(&i.DayKey, &i.SampledAt, &i.Bpm); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeartRateSamplesCompact = `-- name: ListHeartRateSamplesCompact :many
WITH computed AS (
  SELECT
    day_key,
    sampled_at,
    bpm,
    (MIN(sampled_at) OVER(PARTITION BY day_key))::timestamptz as day_start
  FROM heart_rate_samples
  WHERE day_key >= $1 AND day_key <= $2
)
SELECT
  day_key,
  day_start as start_time,
  array_agg(EXTRACT(EPOCH FROM (sampled_at - day_start))::int ORDER BY sampled_at)::int[] as offsets,
  array_agg(bpm::int ORDER BY sampled_at)::int[] as values
FROM computed
GROUP BY day_key, day_start
ORDER BY day_key ASC
`

type ListHeartRateSamplesCompactParams struct {
	DayKey   pgtype.Date `json:"day_key"`
	DayKey_2 pgtype.Date `json:"day_key_2"`
}

type ListHeartRateSamplesCompactRow struct {
	DayKey    pgtype.Date        `json:"day_key"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	Offsets   []int32            `json:"offsets"`
	Values    []int32            `json:"values"`
}

func (q *Queries) ListHeartRateSamplesCompact(ctx context.Context, arg ListHeartRateSamplesCompactParams) ([]ListHeartRateSamplesCompactRow, error) {
	rows, err := q.db.Query(ctx, listHeartRateSamplesCompact, arg.DayKey, arg.DayKey_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHeartRateSamplesCompactRow{}
	for rows.Next() {
		var i ListHeartRateSamplesCompactRow
		if err := rows.Scan(
			&i.DayKey,
			&i.StartTime,
			&i.Offsets,
			&i.Values,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHeartRateSample = `-- name: UpsertHeartRateSample :exec
INSERT INTO heart_rate_samples (sampled_at, day_key, bpm, source_session_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (sampled_at) DO UPDATE SET
  bpm = EXCLUDED.bpm,
  day_key = EXCLUDED.day_key,
  source_session_id = EXCLUDED.source_session_id
`

type UpsertHeartRateSampleParams struct {
	SampledAt       pgtype.Timestamptz `json:"sampled_at"`
	DayKey          pgtype.Date        `json:"day_key"`
	Bpm             int16              `json:"bpm"`
	SourceSessionID string             `json:"source_session_id"`
}

func (q *Queries) UpsertHeartRateSample(ctx context.Context, arg UpsertHeartRateSampleParams) error {
	_, err := q.db.Exec(ctx, upsertHeartRateSample,
		arg.SampledAt,
		arg.DayKey,
		arg.Bpm,
		arg.SourceSessionID,
	)
	return err
}
