// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hrv_samples.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const latestHrvOnDay = `-- name: LatestHrvOnDay :one
SELECT value FROM hrv_samples
WHERE day_key = $1
ORDER BY sampled_at DESC
LIMIT 1
`

func (q *Queries) LatestHrvOnDay(ctx context.Context, dayKey pgtype.Date) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, latestHrvOnDay, dayKey)
	var value pgtype.Numeric
	err := row.Scan(&value)
	return value, err
}

const listHrvSamplesRange = `-- name: ListHrvSamplesRange :many
SELECT sampled_at, day_key, value
FROM hrv_samples
WHERE day_key >= $1 AND day_key <= $2
ORDER BY sampled_at ASC
`

type ListHrvSamplesRangeParams struct {
	DayKey   pgtype.Date `json:"day_key"`
	DayKey_2 pgtype.Date `json:"day_key_2"`
}

type ListHrvSamplesRangeRow struct {
	SampledAt pgtype.Timestamptz `json:"sampled_at"`
	DayKey    pgtype.Date        `json:"day_key"`
	Value     pgtype.Numeric     `json:"value"`
}

func (q *Queries) ListHrvSamplesRange(ctx context.Context, arg ListHrvSamplesRangeParams) ([]ListHrvSamplesRangeRow, error) {
	rows, err := q.db.Query(ctx, listHrvSamplesRange, arg.DayKey, arg.DayKey_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHrvSamplesRangeRow{}
	for rows.Next() {
		var i ListHrvSamplesRangeRow
		if err := rows.Scan(&i.SampledAt, &i.DayKey, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const meanHrvInWindow = `-- name: MeanHrvInWindow :one
SELECT AVG(value)::float8 AS avg_value, COUNT(*) AS n
FROM hrv_samples
WHERE sampled_at >= $1 AND sampled_at <= $2
`

type MeanHrvInWindowParams struct {
	SampledAt   pgtype.Timestamptz `json:"sampled_at"`
	SampledAt_2 pgtype.Timestamptz `json:"sampled_at_2"`
}

type MeanHrvInWindowRow struct {
	AvgValue float64 `json:"avg_value"`
	N        int64   `json:"n"`
}

func (q *Queries) MeanHrvInWindow(ctx context.Context, arg MeanHrvInWindowParams) (MeanHrvInWindowRow, error) {
	row := q.db.QueryRow(ctx, meanHrvInWindow, arg.SampledAt, arg.SampledAt_2)
	var i MeanHrvInWindowRow
	err := row.Scan(&i.AvgValue, &i.N)
	return i, err
}

const upsertHrvSample = `-- name: UpsertHrvSample :exec
INSERT INTO hrv_samples (sampled_at, day_key, value, source_session_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (sampled_at) DO UPDATE SET
  value = EXCLUDED.value,
  day_key = EXCLUDED.day_key,
  source_session_id = EXCLUDED.source_session_id
`

type UpsertHrvSampleParams struct {
	SampledAt       pgtype.Timestamptz `json:"sampled_at"`
	DayKey          pgtype.Date        `json:"day_key"`
	Value           pgtype.Numeric     `json:"value"`
	SourceSessionID string             `json:"source_session_id"`
}

func (q *Queries) UpsertHrvSample(ctx context.Context, arg UpsertHrvSampleParams) error {
	_, err := q.db.Exec(ctx, upsertHrvSample,
		arg.SampledAt,
		arg.DayKey,
		arg.Value,
		arg.SourceSessionID,
	)
	return err
}
