// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DailyMetric struct {
	DayKey         string             `json:"day_key"`
	Steps          int32              `json:"steps"`
	PaiScore       pgtype.Int4        `json:"pai_score"`
	Readiness      pgtype.Int4        `json:"readiness"`
	Spo2Avg        pgtype.Int4        `json:"spo2_avg"`
	HrvRmssd       pgtype.Int4        `json:"hrv_rmssd"`
	RestingHr      pgtype.Int4        `json:"resting_hr"`
	MaxHr          pgtype.Int4        `json:"max_hr"`
	RespRateAvg    pgtype.Int4        `json:"resp_rate_avg"`
	StressAvg      pgtype.Int4        `json:"stress_avg"`
	SleepScore     pgtype.Int4        `json:"sleep_score"`
	SleepMins      pgtype.Int4        `json:"sleep_mins"`
	SleepDeepMins  pgtype.Int4        `json:"sleep_deep_mins"`
	SleepRemMins   pgtype.Int4        `json:"sleep_rem_mins"`
	SleepLightMins pgtype.Int4        `json:"sleep_light_mins"`
	TempAvgC       pgtype.Numeric     `json:"temp_avg_c"`
	NapCount             int32              `json:"nap_count"`
	WorkoutCount         int32              `json:"workout_count"`
	ActivitySessionCount int32              `json:"activity_session_count"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type HealthSample struct {
	ID            int64              `json:"id"`
	SyncSessionID string             `json:"sync_session_id"`
	Metric        string             `json:"metric"`
	DayKey        string             `json:"day_key"`
	SampledAt     pgtype.Timestamptz `json:"sampled_at"`
	Value         pgtype.Numeric     `json:"value"`
}

type RawTypeBlob struct {
	SessionID string `json:"session_id"`
	TypeCode  string `json:"type_code"`
	ByteLen   int32  `json:"byte_len"`
	Payload   []byte `json:"payload"`
}

type SleepSession struct {
	ID            int64              `json:"id"`
	SyncSessionID string             `json:"sync_session_id"`
	DayKey        string             `json:"day_key"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	Score         int32              `json:"score"`
	TotalMins     int32              `json:"total_mins"`
	DeepMins      int32              `json:"deep_mins"`
	RemMins       int32              `json:"rem_mins"`
	LightMins     int32              `json:"light_mins"`
}

type SyncSession struct {
	SessionID   string             `json:"session_id"`
	DeviceMac   pgtype.Text        `json:"device_mac"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
	BatteryPct  pgtype.Int4        `json:"battery_pct"`
	CatalogJson []byte             `json:"catalog_json"`
	IngestedAt  pgtype.Timestamptz `json:"ingested_at"`
}

type TemperatureSample struct {
	ID            int64              `json:"id"`
	SyncSessionID string             `json:"sync_session_id"`
	DayKey        string             `json:"day_key"`
	SampledAt     pgtype.Timestamptz `json:"sampled_at"`
	Celsius       pgtype.Numeric     `json:"celsius"`
}

type Workout struct {
	ID            int64              `json:"id"`
	SyncSessionID string             `json:"sync_session_id"`
	DayKey        string             `json:"day_key"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	SportType     int32              `json:"sport_type"`
	SportName     pgtype.Text        `json:"sport_name"`
	DurationSec   int32              `json:"duration_sec"`
	Calories      pgtype.Int4        `json:"calories"`
	AvgHr         pgtype.Int4        `json:"avg_hr"`
	MaxHr         pgtype.Int4        `json:"max_hr"`
}

type ActivitySession struct {
	ID            int64              `json:"id"`
	SyncSessionID string             `json:"sync_session_id"`
	DayKey        string             `json:"day_key"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	SportType     int32              `json:"sport_type"`
	SportName     pgtype.Text        `json:"sport_name"`
	DurationSec   int32              `json:"duration_sec"`
	Calories      pgtype.Int4        `json:"calories"`
	AvgHr         pgtype.Int4        `json:"avg_hr"`
	MaxHr         pgtype.Int4        `json:"max_hr"`
}
