// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProfile = `-- name: GetProfile :one
SELECT id, name, age, height_cm, weight_kg, created_at, updated_at
FROM profiles WHERE id = 1
`

// Single-row table: always id=1.
func (q *Queries) GetProfile(ctx context.Context) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Age,
		&i.HeightCm,
		&i.WeightKg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProfile = `-- name: UpsertProfile :exec
INSERT INTO profiles (id, name, age, height_cm, weight_kg, updated_at)
VALUES (1, $1, $2, $3, $4, NOW())
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  age = EXCLUDED.age,
  height_cm = EXCLUDED.height_cm,
  weight_kg = EXCLUDED.weight_kg,
  updated_at = NOW()
`

type UpsertProfileParams struct {
	Name     pgtype.Text    `json:"name"`
	Age      pgtype.Int4    `json:"age"`
	HeightCm pgtype.Numeric `json:"height_cm"`
	WeightKg pgtype.Numeric `json:"weight_kg"`
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) error {
	_, err := q.db.Exec(ctx, upsertProfile,
		arg.Name,
		arg.Age,
		arg.HeightCm,
		arg.WeightKg,
	)
	return err
}
