// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: raw_pai_scores.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRawPaiScore = `-- name: GetRawPaiScore :one
SELECT day_key, score FROM raw_pai_scores WHERE day_key = $1
`

type GetRawPaiScoreRow struct {
	DayKey pgtype.Date `json:"day_key"`
	Score  int32       `json:"score"`
}

func (q *Queries) GetRawPaiScore(ctx context.Context, dayKey pgtype.Date) (GetRawPaiScoreRow, error) {
	row := q.db.QueryRow(ctx, getRawPaiScore, dayKey)
	var i GetRawPaiScoreRow
	err := row.Scan(&i.DayKey, &i.Score)
	return i, err
}

const upsertRawPaiScore = `-- name: UpsertRawPaiScore :exec
INSERT INTO raw_pai_scores (day_key, score, source_session_id, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (day_key) DO UPDATE SET
  score = EXCLUDED.score,
  source_session_id = EXCLUDED.source_session_id,
  updated_at = NOW()
`

type UpsertRawPaiScoreParams struct {
	DayKey          pgtype.Date `json:"day_key"`
	Score           int32       `json:"score"`
	SourceSessionID string      `json:"source_session_id"`
}

func (q *Queries) UpsertRawPaiScore(ctx context.Context, arg UpsertRawPaiScoreParams) error {
	_, err := q.db.Exec(ctx, upsertRawPaiScore, arg.DayKey, arg.Score, arg.SourceSessionID)
	return err
}
