// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: raw_readiness.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRawReadiness = `-- name: GetRawReadiness :one
SELECT day_key, score FROM raw_readiness WHERE day_key = $1
`

type GetRawReadinessRow struct {
	DayKey pgtype.Date `json:"day_key"`
	Score  int32       `json:"score"`
}

func (q *Queries) GetRawReadiness(ctx context.Context, dayKey pgtype.Date) (GetRawReadinessRow, error) {
	row := q.db.QueryRow(ctx, getRawReadiness, dayKey)
	var i GetRawReadinessRow
	err := row.Scan(&i.DayKey, &i.Score)
	return i, err
}

const upsertRawReadiness = `-- name: UpsertRawReadiness :exec
INSERT INTO raw_readiness (day_key, score, source_session_id, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (day_key) DO UPDATE SET
  score = EXCLUDED.score,
  source_session_id = EXCLUDED.source_session_id,
  updated_at = NOW()
`

type UpsertRawReadinessParams struct {
	DayKey          pgtype.Date `json:"day_key"`
	Score           int32       `json:"score"`
	SourceSessionID string      `json:"source_session_id"`
}

func (q *Queries) UpsertRawReadiness(ctx context.Context, arg UpsertRawReadinessParams) error {
	_, err := q.db.Exec(ctx, upsertRawReadiness, arg.DayKey, arg.Score, arg.SourceSessionID)
	return err
}
