// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resp_samples.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const latestRespOnDay = `-- name: LatestRespOnDay :one
SELECT value FROM resp_samples
WHERE day_key = $1
ORDER BY sampled_at DESC
LIMIT 1
`

func (q *Queries) LatestRespOnDay(ctx context.Context, dayKey pgtype.Date) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, latestRespOnDay, dayKey)
	var value pgtype.Numeric
	err := row.Scan(&value)
	return value, err
}

const listRespSamplesRange = `-- name: ListRespSamplesRange :many
SELECT sampled_at, day_key, value
FROM resp_samples
WHERE day_key >= $1 AND day_key <= $2
ORDER BY sampled_at ASC
`

type ListRespSamplesRangeParams struct {
	DayKey   pgtype.Date `json:"day_key"`
	DayKey_2 pgtype.Date `json:"day_key_2"`
}

type ListRespSamplesRangeRow struct {
	SampledAt pgtype.Timestamptz `json:"sampled_at"`
	DayKey    pgtype.Date        `json:"day_key"`
	Value     pgtype.Numeric     `json:"value"`
}

func (q *Queries) ListRespSamplesRange(ctx context.Context, arg ListRespSamplesRangeParams) ([]ListRespSamplesRangeRow, error) {
	rows, err := q.db.Query(ctx, listRespSamplesRange, arg.DayKey, arg.DayKey_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRespSamplesRangeRow{}
	for rows.Next() {
		var i ListRespSamplesRangeRow
		if err := rows.Scan(&i.SampledAt, &i.DayKey, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const meanRespInWindow = `-- name: MeanRespInWindow :one
SELECT AVG(value)::float8 AS avg_value, COUNT(*) AS n
FROM resp_samples
WHERE sampled_at >= $1 AND sampled_at <= $2
`

type MeanRespInWindowParams struct {
	SampledAt   pgtype.Timestamptz `json:"sampled_at"`
	SampledAt_2 pgtype.Timestamptz `json:"sampled_at_2"`
}

type MeanRespInWindowRow struct {
	AvgValue float64 `json:"avg_value"`
	N        int64   `json:"n"`
}

func (q *Queries) MeanRespInWindow(ctx context.Context, arg MeanRespInWindowParams) (MeanRespInWindowRow, error) {
	row := q.db.QueryRow(ctx, meanRespInWindow, arg.SampledAt, arg.SampledAt_2)
	var i MeanRespInWindowRow
	err := row.Scan(&i.AvgValue, &i.N)
	return i, err
}

const upsertRespSample = `-- name: UpsertRespSample :exec
INSERT INTO resp_samples (sampled_at, day_key, value, source_session_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (sampled_at) DO UPDATE SET
  value = EXCLUDED.value,
  day_key = EXCLUDED.day_key,
  source_session_id = EXCLUDED.source_session_id
`

type UpsertRespSampleParams struct {
	SampledAt       pgtype.Timestamptz `json:"sampled_at"`
	DayKey          pgtype.Date        `json:"day_key"`
	Value           pgtype.Numeric     `json:"value"`
	SourceSessionID string             `json:"source_session_id"`
}

func (q *Queries) UpsertRespSample(ctx context.Context, arg UpsertRespSampleParams) error {
	_, err := q.db.Exec(ctx, upsertRespSample,
		arg.SampledAt,
		arg.DayKey,
		arg.Value,
		arg.SourceSessionID,
	)
	return err
}
