// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rhr_samples.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const latestRhrOnDay = `-- name: LatestRhrOnDay :one
SELECT value FROM rhr_samples
WHERE day_key = $1
ORDER BY sampled_at DESC
LIMIT 1
`

func (q *Queries) LatestRhrOnDay(ctx context.Context, dayKey pgtype.Date) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, latestRhrOnDay, dayKey)
	var value pgtype.Numeric
	err := row.Scan(&value)
	return value, err
}

const listRhrSamplesRange = `-- name: ListRhrSamplesRange :many
SELECT sampled_at, day_key, value
FROM rhr_samples
WHERE day_key >= $1 AND day_key <= $2
ORDER BY sampled_at ASC
`

type ListRhrSamplesRangeParams struct {
	DayKey   pgtype.Date `json:"day_key"`
	DayKey_2 pgtype.Date `json:"day_key_2"`
}

type ListRhrSamplesRangeRow struct {
	SampledAt pgtype.Timestamptz `json:"sampled_at"`
	DayKey    pgtype.Date        `json:"day_key"`
	Value     pgtype.Numeric     `json:"value"`
}

func (q *Queries) ListRhrSamplesRange(ctx context.Context, arg ListRhrSamplesRangeParams) ([]ListRhrSamplesRangeRow, error) {
	rows, err := q.db.Query(ctx, listRhrSamplesRange, arg.DayKey, arg.DayKey_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRhrSamplesRangeRow{}
	for rows.Next() {
		var i ListRhrSamplesRangeRow
		if err := rows.Scan(&i.SampledAt, &i.DayKey, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const meanRhrInWindow = `-- name: MeanRhrInWindow :one
SELECT AVG(value)::float8 AS avg_value, COUNT(*) AS n
FROM rhr_samples
WHERE sampled_at >= $1 AND sampled_at <= $2
`

type MeanRhrInWindowParams struct {
	SampledAt   pgtype.Timestamptz `json:"sampled_at"`
	SampledAt_2 pgtype.Timestamptz `json:"sampled_at_2"`
}

type MeanRhrInWindowRow struct {
	AvgValue float64 `json:"avg_value"`
	N        int64   `json:"n"`
}

func (q *Queries) MeanRhrInWindow(ctx context.Context, arg MeanRhrInWindowParams) (MeanRhrInWindowRow, error) {
	row := q.db.QueryRow(ctx, meanRhrInWindow, arg.SampledAt, arg.SampledAt_2)
	var i MeanRhrInWindowRow
	err := row.Scan(&i.AvgValue, &i.N)
	return i, err
}

const upsertRhrSample = `-- name: UpsertRhrSample :exec
INSERT INTO rhr_samples (sampled_at, day_key, value, source_session_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (sampled_at) DO UPDATE SET
  value = EXCLUDED.value,
  day_key = EXCLUDED.day_key,
  source_session_id = EXCLUDED.source_session_id
`

type UpsertRhrSampleParams struct {
	SampledAt       pgtype.Timestamptz `json:"sampled_at"`
	DayKey          pgtype.Date        `json:"day_key"`
	Value           pgtype.Numeric     `json:"value"`
	SourceSessionID string             `json:"source_session_id"`
}

func (q *Queries) UpsertRhrSample(ctx context.Context, arg UpsertRhrSampleParams) error {
	_, err := q.db.Exec(ctx, upsertRhrSample,
		arg.SampledAt,
		arg.DayKey,
		arg.Value,
		arg.SourceSessionID,
	)
	return err
}
