// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sleep.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSleepBySession = `-- name: DeleteSleepBySession :exec
DELETE FROM sleep_sessions WHERE sync_session_id = $1
`

func (q *Queries) DeleteSleepBySession(ctx context.Context, syncSessionID string) error {
	_, err := q.db.Exec(ctx, deleteSleepBySession, syncSessionID)
	return err
}

const listSleep = `-- name: ListSleep :many
SELECT day_key, started_at, score, total_mins, deep_mins, rem_mins, light_mins,
       wake_mins, is_nap, stages_json
FROM sleep_sessions
WHERE day_key >= $1 AND day_key <= $2
ORDER BY started_at DESC
`

type ListSleepParams struct {
	DayKey   string `json:"day_key"`
	DayKey_2 string `json:"day_key_2"`
}

type ListSleepRow struct {
	DayKey     string             `json:"day_key"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	Score      int32              `json:"score"`
	TotalMins  int32              `json:"total_mins"`
	DeepMins   int32              `json:"deep_mins"`
	RemMins    int32              `json:"rem_mins"`
	LightMins  int32              `json:"light_mins"`
	WakeMins   int32              `json:"wake_mins"`
	IsNap      bool               `json:"is_nap"`
	StagesJson []byte             `json:"stages_json"`
}

func (q *Queries) ListSleep(ctx context.Context, arg ListSleepParams) ([]ListSleepRow, error) {
	rows, err := q.db.Query(ctx, listSleep, arg.DayKey, arg.DayKey_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSleepRow{}
	for rows.Next() {
		var i ListSleepRow
		if err := rows.Scan(
			&i.DayKey,
			&i.StartedAt,
			&i.Score,
			&i.TotalMins,
			&i.DeepMins,
			&i.RemMins,
			&i.LightMins,
			&i.WakeMins,
			&i.IsNap,
			&i.StagesJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSleepSession = `-- name: UpsertSleepSession :exec
INSERT INTO sleep_sessions (sync_session_id, day_key, started_at, score,
  total_mins, deep_mins, rem_mins, light_mins, wake_mins, is_nap, stages_json)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (sync_session_id, started_at) DO UPDATE SET
  score = EXCLUDED.score,
  total_mins = EXCLUDED.total_mins,
  deep_mins = EXCLUDED.deep_mins,
  rem_mins = EXCLUDED.rem_mins,
  light_mins = EXCLUDED.light_mins,
  wake_mins = EXCLUDED.wake_mins,
  is_nap = EXCLUDED.is_nap,
  stages_json = EXCLUDED.stages_json
`

type UpsertSleepSessionParams struct {
	SyncSessionID string             `json:"sync_session_id"`
	DayKey        string             `json:"day_key"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	Score         int32              `json:"score"`
	TotalMins     int32              `json:"total_mins"`
	DeepMins      int32              `json:"deep_mins"`
	RemMins       int32              `json:"rem_mins"`
	LightMins     int32              `json:"light_mins"`
	WakeMins      int32              `json:"wake_mins"`
	IsNap         bool               `json:"is_nap"`
	StagesJson    []byte             `json:"stages_json"`
}

func (q *Queries) UpsertSleepSession(ctx context.Context, arg UpsertSleepSessionParams) error {
	_, err := q.db.Exec(ctx, upsertSleepSession,
		arg.SyncSessionID,
		arg.DayKey,
		arg.StartedAt,
		arg.Score,
		arg.TotalMins,
		arg.DeepMins,
		arg.RemMins,
		arg.LightMins,
		arg.WakeMins,
		arg.IsNap,
		arg.StagesJson,
	)
	return err
}
