// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spo2_samples.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const latestSpo2OnDay = `-- name: LatestSpo2OnDay :one
SELECT value FROM spo2_samples
WHERE day_key = $1
ORDER BY sampled_at DESC
LIMIT 1
`

func (q *Queries) LatestSpo2OnDay(ctx context.Context, dayKey pgtype.Date) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, latestSpo2OnDay, dayKey)
	var value pgtype.Numeric
	err := row.Scan(&value)
	return value, err
}

const listSpo2SamplesRange = `-- name: ListSpo2SamplesRange :many
SELECT sampled_at, day_key, value
FROM spo2_samples
WHERE day_key >= $1 AND day_key <= $2
ORDER BY sampled_at ASC
`

type ListSpo2SamplesRangeParams struct {
	DayKey   pgtype.Date `json:"day_key"`
	DayKey_2 pgtype.Date `json:"day_key_2"`
}

type ListSpo2SamplesRangeRow struct {
	SampledAt pgtype.Timestamptz `json:"sampled_at"`
	DayKey    pgtype.Date        `json:"day_key"`
	Value     pgtype.Numeric     `json:"value"`
}

func (q *Queries) ListSpo2SamplesRange(ctx context.Context, arg ListSpo2SamplesRangeParams) ([]ListSpo2SamplesRangeRow, error) {
	rows, err := q.db.Query(ctx, listSpo2SamplesRange, arg.DayKey, arg.DayKey_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSpo2SamplesRangeRow{}
	for rows.Next() {
		var i ListSpo2SamplesRangeRow
		if err := rows.Scan(&i.SampledAt, &i.DayKey, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const meanSpo2InWindow = `-- name: MeanSpo2InWindow :one
SELECT AVG(value)::float8 AS avg_value, COUNT(*) AS n
FROM spo2_samples
WHERE sampled_at >= $1 AND sampled_at <= $2
`

type MeanSpo2InWindowParams struct {
	SampledAt   pgtype.Timestamptz `json:"sampled_at"`
	SampledAt_2 pgtype.Timestamptz `json:"sampled_at_2"`
}

type MeanSpo2InWindowRow struct {
	AvgValue float64 `json:"avg_value"`
	N        int64   `json:"n"`
}

func (q *Queries) MeanSpo2InWindow(ctx context.Context, arg MeanSpo2InWindowParams) (MeanSpo2InWindowRow, error) {
	row := q.db.QueryRow(ctx, meanSpo2InWindow, arg.SampledAt, arg.SampledAt_2)
	var i MeanSpo2InWindowRow
	err := row.Scan(&i.AvgValue, &i.N)
	return i, err
}

const upsertSpo2Sample = `-- name: UpsertSpo2Sample :exec
INSERT INTO spo2_samples (sampled_at, day_key, value, source_session_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (sampled_at) DO UPDATE SET
  value = EXCLUDED.value,
  day_key = EXCLUDED.day_key,
  source_session_id = EXCLUDED.source_session_id
`

type UpsertSpo2SampleParams struct {
	SampledAt       pgtype.Timestamptz `json:"sampled_at"`
	DayKey          pgtype.Date        `json:"day_key"`
	Value           pgtype.Numeric     `json:"value"`
	SourceSessionID string             `json:"source_session_id"`
}

func (q *Queries) UpsertSpo2Sample(ctx context.Context, arg UpsertSpo2SampleParams) error {
	_, err := q.db.Exec(ctx, upsertSpo2Sample,
		arg.SampledAt,
		arg.DayKey,
		arg.Value,
		arg.SourceSessionID,
	)
	return err
}
