// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stress_samples.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const latestStressOnDay = `-- name: LatestStressOnDay :one
SELECT value FROM stress_samples
WHERE day_key = $1
ORDER BY sampled_at DESC
LIMIT 1
`

func (q *Queries) LatestStressOnDay(ctx context.Context, dayKey pgtype.Date) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, latestStressOnDay, dayKey)
	var value pgtype.Numeric
	err := row.Scan(&value)
	return value, err
}

const listStressSamplesRange = `-- name: ListStressSamplesRange :many
SELECT sampled_at, day_key, value
FROM stress_samples
WHERE day_key >= $1 AND day_key <= $2
ORDER BY sampled_at ASC
`

type ListStressSamplesRangeParams struct {
	DayKey   pgtype.Date `json:"day_key"`
	DayKey_2 pgtype.Date `json:"day_key_2"`
}

type ListStressSamplesRangeRow struct {
	SampledAt pgtype.Timestamptz `json:"sampled_at"`
	DayKey    pgtype.Date        `json:"day_key"`
	Value     pgtype.Numeric     `json:"value"`
}

func (q *Queries) ListStressSamplesRange(ctx context.Context, arg ListStressSamplesRangeParams) ([]ListStressSamplesRangeRow, error) {
	rows, err := q.db.Query(ctx, listStressSamplesRange, arg.DayKey, arg.DayKey_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStressSamplesRangeRow{}
	for rows.Next() {
		var i ListStressSamplesRangeRow
		if err := rows.Scan(&i.SampledAt, &i.DayKey, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const meanStressInWindow = `-- name: MeanStressInWindow :one
SELECT AVG(value)::float8 AS avg_value, COUNT(*) AS n
FROM stress_samples
WHERE sampled_at >= $1 AND sampled_at <= $2
`

type MeanStressInWindowParams struct {
	SampledAt   pgtype.Timestamptz `json:"sampled_at"`
	SampledAt_2 pgtype.Timestamptz `json:"sampled_at_2"`
}

type MeanStressInWindowRow struct {
	AvgValue float64 `json:"avg_value"`
	N        int64   `json:"n"`
}

func (q *Queries) MeanStressInWindow(ctx context.Context, arg MeanStressInWindowParams) (MeanStressInWindowRow, error) {
	row := q.db.QueryRow(ctx, meanStressInWindow, arg.SampledAt, arg.SampledAt_2)
	var i MeanStressInWindowRow
	err := row.Scan(&i.AvgValue, &i.N)
	return i, err
}

const upsertStressSample = `-- name: UpsertStressSample :exec
INSERT INTO stress_samples (sampled_at, day_key, value, source_session_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (sampled_at) DO UPDATE SET
  value = EXCLUDED.value,
  day_key = EXCLUDED.day_key,
  source_session_id = EXCLUDED.source_session_id
`

type UpsertStressSampleParams struct {
	SampledAt       pgtype.Timestamptz `json:"sampled_at"`
	DayKey          pgtype.Date        `json:"day_key"`
	Value           pgtype.Numeric     `json:"value"`
	SourceSessionID string             `json:"source_session_id"`
}

func (q *Queries) UpsertStressSample(ctx context.Context, arg UpsertStressSampleParams) error {
	_, err := q.db.Exec(ctx, upsertStressSample,
		arg.SampledAt,
		arg.DayKey,
		arg.Value,
		arg.SourceSessionID,
	)
	return err
}
