// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: temperature.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTemperatureBySession = `-- name: DeleteTemperatureBySession :exec
DELETE FROM temperature_samples WHERE sync_session_id = $1
`

func (q *Queries) DeleteTemperatureBySession(ctx context.Context, syncSessionID string) error {
	_, err := q.db.Exec(ctx, deleteTemperatureBySession, syncSessionID)
	return err
}

const insertTemperatureSample = `-- name: InsertTemperatureSample :exec
INSERT INTO temperature_samples (sync_session_id, day_key, sampled_at, celsius)
VALUES ($1, $2, $3, $4)
`

type InsertTemperatureSampleParams struct {
	SyncSessionID string             `json:"sync_session_id"`
	DayKey        string             `json:"day_key"`
	SampledAt     pgtype.Timestamptz `json:"sampled_at"`
	Celsius       pgtype.Numeric     `json:"celsius"`
}

func (q *Queries) InsertTemperatureSample(ctx context.Context, arg InsertTemperatureSampleParams) error {
	_, err := q.db.Exec(ctx, insertTemperatureSample,
		arg.SyncSessionID,
		arg.DayKey,
		arg.SampledAt,
		arg.Celsius,
	)
	return err
}

const listTemperature = `-- name: ListTemperature :many
SELECT day_key, sampled_at, celsius
FROM temperature_samples
WHERE day_key >= $1 AND day_key <= $2
ORDER BY sampled_at ASC
`

type ListTemperatureParams struct {
	DayKey   string `json:"day_key"`
	DayKey_2 string `json:"day_key_2"`
}

type ListTemperatureRow struct {
	DayKey    string             `json:"day_key"`
	SampledAt pgtype.Timestamptz `json:"sampled_at"`
	Celsius   pgtype.Numeric     `json:"celsius"`
}

func (q *Queries) ListTemperature(ctx context.Context, arg ListTemperatureParams) ([]ListTemperatureRow, error) {
	rows, err := q.db.Query(ctx, listTemperature, arg.DayKey, arg.DayKey_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTemperatureRow{}
	for rows.Next() {
		var i ListTemperatureRow
		if err := rows.Scan(&i.DayKey, &i.SampledAt, &i.Celsius); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
