// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workouts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listWorkouts = `-- name: ListWorkouts :many
SELECT day_key, started_at, sport_type, sport_name,
       duration_sec, calories, avg_hr, max_hr
FROM workouts
WHERE day_key >= $1 AND day_key <= $2
ORDER BY started_at DESC
`

type ListWorkoutsParams struct {
	DayKey   pgtype.Date `json:"day_key"`
	DayKey_2 pgtype.Date `json:"day_key_2"`
}

type ListWorkoutsRow struct {
	DayKey      pgtype.Date        `json:"day_key"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	SportType   int32              `json:"sport_type"`
	SportName   pgtype.Text        `json:"sport_name"`
	DurationSec int32              `json:"duration_sec"`
	Calories    pgtype.Int4        `json:"calories"`
	AvgHr       pgtype.Int4        `json:"avg_hr"`
	MaxHr       pgtype.Int4        `json:"max_hr"`
}

func (q *Queries) ListWorkouts(ctx context.Context, arg ListWorkoutsParams) ([]ListWorkoutsRow, error) {
	rows, err := q.db.Query(ctx, listWorkouts, arg.DayKey, arg.DayKey_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkoutsRow{}
	for rows.Next() {
		var i ListWorkoutsRow
		if err := rows.Scan(
			&i.DayKey,
			&i.StartedAt,
			&i.SportType,
			&i.SportName,
			&i.DurationSec,
			&i.Calories,
			&i.AvgHr,
			&i.MaxHr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWorkout = `-- name: UpsertWorkout :exec
INSERT INTO workouts (source_session_id, day_key, started_at, sport_type,
  sport_name, duration_sec, calories, avg_hr, max_hr, has_summary, has_detail)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (day_key, started_at) DO UPDATE SET
  source_session_id = EXCLUDED.source_session_id,
  sport_type = CASE WHEN EXCLUDED.has_summary THEN EXCLUDED.sport_type ELSE workouts.sport_type END,
  sport_name = CASE WHEN EXCLUDED.has_summary THEN EXCLUDED.sport_name ELSE workouts.sport_name END,
  duration_sec = CASE WHEN EXCLUDED.has_summary OR NOT workouts.has_summary THEN EXCLUDED.duration_sec ELSE workouts.duration_sec END,
  calories = COALESCE(EXCLUDED.calories, workouts.calories),
  avg_hr = COALESCE(EXCLUDED.avg_hr, workouts.avg_hr),
  max_hr = COALESCE(EXCLUDED.max_hr, workouts.max_hr),
  has_summary = workouts.has_summary OR EXCLUDED.has_summary,
  has_detail = workouts.has_detail OR EXCLUDED.has_detail,
  updated_at = NOW()
`

type UpsertWorkoutParams struct {
	SourceSessionID string             `json:"source_session_id"`
	DayKey          pgtype.Date        `json:"day_key"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	SportType       int32              `json:"sport_type"`
	SportName       pgtype.Text        `json:"sport_name"`
	DurationSec     int32              `json:"duration_sec"`
	Calories        pgtype.Int4        `json:"calories"`
	AvgHr           pgtype.Int4        `json:"avg_hr"`
	MaxHr           pgtype.Int4        `json:"max_hr"`
	HasSummary      bool               `json:"has_summary"`
	HasDetail       bool               `json:"has_detail"`
}

func (q *Queries) UpsertWorkout(ctx context.Context, arg UpsertWorkoutParams) error {
	_, err := q.db.Exec(ctx, upsertWorkout,
		arg.SourceSessionID,
		arg.DayKey,
		arg.StartedAt,
		arg.SportType,
		arg.SportName,
		arg.DurationSec,
		arg.Calories,
		arg.AvgHr,
		arg.MaxHr,
		arg.HasSummary,
		arg.HasDetail,
	)
	return err
}
