// Code generated by sqlc. DO NOT EDIT.
// source: workouts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listWorkouts = `-- name: ListWorkouts :many
SELECT day_key, started_at, sport_type, sport_name,
       duration_sec, calories, avg_hr, max_hr
FROM workouts
WHERE day_key >= $1 AND day_key <= $2
ORDER BY started_at DESC
`

type ListWorkoutsParams struct {
	DayKey   pgtype.Date `json:"day_key"`
	DayKey_2 pgtype.Date `json:"day_key_2"`
}

type ListWorkoutsRow struct {
	DayKey      pgtype.Date        `json:"day_key"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	SportType   int32              `json:"sport_type"`
	SportName   pgtype.Text        `json:"sport_name"`
	DurationSec int32              `json:"duration_sec"`
	Calories    pgtype.Int4        `json:"calories"`
	AvgHr       pgtype.Int4        `json:"avg_hr"`
	MaxHr       pgtype.Int4        `json:"max_hr"`
}

func (q *Queries) ListWorkouts(ctx context.Context, arg ListWorkoutsParams) ([]ListWorkoutsRow, error) {
	rows, err := q.db.Query(ctx, listWorkouts, arg.DayKey, arg.DayKey_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkoutsRow{}
	for rows.Next() {
		var i ListWorkoutsRow
		if err := rows.Scan(
			&i.DayKey, &i.StartedAt, &i.SportType, &i.SportName,
			&i.DurationSec, &i.Calories, &i.AvgHr, &i.MaxHr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const upsertWorkout = `-- name: UpsertWorkout :exec
INSERT INTO workouts (source_session_id, day_key, started_at, sport_type,
  sport_name, duration_sec, calories, avg_hr, max_hr)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (day_key, started_at) DO UPDATE SET
  source_session_id = EXCLUDED.source_session_id,
  sport_name = EXCLUDED.sport_name,
  duration_sec = EXCLUDED.duration_sec,
  calories = EXCLUDED.calories,
  avg_hr = EXCLUDED.avg_hr,
  max_hr = EXCLUDED.max_hr,
  updated_at = NOW()
`

type UpsertWorkoutParams struct {
	SourceSessionID string             `json:"source_session_id"`
	DayKey          pgtype.Date        `json:"day_key"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	SportType       int32              `json:"sport_type"`
	SportName       pgtype.Text        `json:"sport_name"`
	DurationSec     int32              `json:"duration_sec"`
	Calories        pgtype.Int4        `json:"calories"`
	AvgHr           pgtype.Int4        `json:"avg_hr"`
	MaxHr           pgtype.Int4        `json:"max_hr"`
}

func (q *Queries) UpsertWorkout(ctx context.Context, arg UpsertWorkoutParams) error {
	_, err := q.db.Exec(ctx, upsertWorkout,
		arg.SourceSessionID, arg.DayKey, arg.StartedAt, arg.SportType, arg.SportName,
		arg.DurationSec, arg.Calories, arg.AvgHr, arg.MaxHr,
	)
	return err
}
