// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workouts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteWorkoutsBySession = `-- name: DeleteWorkoutsBySession :exec
DELETE FROM workouts WHERE sync_session_id = $1
`

func (q *Queries) DeleteWorkoutsBySession(ctx context.Context, syncSessionID string) error {
	_, err := q.db.Exec(ctx, deleteWorkoutsBySession, syncSessionID)
	return err
}

const listWorkouts = `-- name: ListWorkouts :many
SELECT sync_session_id, day_key, started_at, sport_type, sport_name,
       duration_sec, calories, avg_hr, max_hr
FROM workouts
WHERE day_key >= $1 AND day_key <= $2
ORDER BY started_at DESC
`

type ListWorkoutsParams struct {
	DayKey   string `json:"day_key"`
	DayKey_2 string `json:"day_key_2"`
}

type ListWorkoutsRow struct {
	SyncSessionID string             `json:"sync_session_id"`
	DayKey        string             `json:"day_key"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	SportType     int32              `json:"sport_type"`
	SportName     pgtype.Text        `json:"sport_name"`
	DurationSec   int32              `json:"duration_sec"`
	Calories      pgtype.Int4        `json:"calories"`
	AvgHr         pgtype.Int4        `json:"avg_hr"`
	MaxHr         pgtype.Int4        `json:"max_hr"`
}

func (q *Queries) ListWorkouts(ctx context.Context, arg ListWorkoutsParams) ([]ListWorkoutsRow, error) {
	rows, err := q.db.Query(ctx, listWorkouts, arg.DayKey, arg.DayKey_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkoutsRow{}
	for rows.Next() {
		var i ListWorkoutsRow
		if err := rows.Scan(
			&i.SyncSessionID,
			&i.DayKey,
			&i.StartedAt,
			&i.SportType,
			&i.SportName,
			&i.DurationSec,
			&i.Calories,
			&i.AvgHr,
			&i.MaxHr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWorkout = `-- name: UpsertWorkout :exec
INSERT INTO workouts (sync_session_id, day_key, started_at, sport_type,
  sport_name, duration_sec, calories, avg_hr, max_hr)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (sync_session_id, started_at) DO UPDATE SET
  sport_name = EXCLUDED.sport_name,
  duration_sec = EXCLUDED.duration_sec,
  calories = EXCLUDED.calories,
  avg_hr = EXCLUDED.avg_hr,
  max_hr = EXCLUDED.max_hr
`

type UpsertWorkoutParams struct {
	SyncSessionID string             `json:"sync_session_id"`
	DayKey        string             `json:"day_key"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	SportType     int32              `json:"sport_type"`
	SportName     pgtype.Text        `json:"sport_name"`
	DurationSec   int32              `json:"duration_sec"`
	Calories      pgtype.Int4        `json:"calories"`
	AvgHr         pgtype.Int4        `json:"avg_hr"`
	MaxHr         pgtype.Int4        `json:"max_hr"`
}

func (q *Queries) UpsertWorkout(ctx context.Context, arg UpsertWorkoutParams) error {
	_, err := q.db.Exec(ctx, upsertWorkout,
		arg.SyncSessionID,
		arg.DayKey,
		arg.StartedAt,
		arg.SportType,
		arg.SportName,
		arg.DurationSec,
		arg.Calories,
		arg.AvgHr,
		arg.MaxHr,
	)
	return err
}
